name: Publish to crates.io

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Ensure tag is on main
        run: |
          # Atualiza a main local
          git fetch origin main --depth=1

          echo "Checking if tag commit is reachable from main..."
          git branch --contains $GITHUB_SHA | grep main || {
            echo "❌ Tag is NOT on main! Aborting publish."
            exit 1
          }

          echo "✅ Tag is on main. Proceeding."

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Login to crates.io
        run: cargo login $CARGO_REGISTRY_TOKEN
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish crate
        run: cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
