name: Publish to crates.io

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch main
        run: |
          git fetch origin +refs/heads/main:refs/remotes/origin/main --depth=1

      - name: Ensure tag is on main
        run: |
          echo "HEAD:        $(git rev-parse HEAD)"
          echo "MAIN REMOTE: $(git rev-parse origin/main)"

          git merge-base --is-ancestor HEAD origin/main || {
            echo "❌ Tag commit is NOT in main"
            exit 1
          }

          echo "✅ Tag commit is in main"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Login
        run: cargo login $CARGO_REGISTRY_TOKEN
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish
        run: cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
